### ISSUE TITLE
bqskitrs on macOS / python3.8 download problem

### ISSUE THREAD

**Issue by natestemen** [BQSKit/bqskitrs#10]
Hey, we are trying to support python 3.11 over on Mitiq, but for some reason bqskit 1.0.4 is failing to build on python 3.8 (macOS) due to pip being unable to find `bqskitrs == 0.3.0`. [Here's](https://github.com/unitaryfund/mitiq/actions/runs/4238034684/jobs/7364661468#step:4:120) the log, but the relevant lines are:
```
ERROR: Could not find a version that satisfies the requirement bqskitrs>=0.3.0 (from bqskit) (from versions: 0.1.0a2, 0.1.0a3, 0.1.0a4, 0.1.0b1, 0.1.0b2, 0.2.0rc2, 0.2.0, 0.2.2, 0.2.3, 0.3.0rc1)
ERROR: No matching distribution found for bqskitrs>=0.3.0
```
BQSKit is pinned to `bqskit==1.0.4`.

 I can't seem to make heads or tails of this one since I can download `bqskitrs==0.3.0`, locally, and it shows published on pypi.  Was hoping someone here would be able to provide some insight.

**Comment by natestemen** [comment]
I've [loosened the BQSKit](https://github.com/unitaryfund/mitiq/actions/runs/4238105114/jobs/7364810455) requirement to `bqskit>=1.0.0` and `bqskit==1.0.3` was downloaded with `bqskitrs==0.2.3`. So that's a viable workaround for now.

Still, would love to know what you think is going on for the above issue.

**Comment by edyounis** [comment]
What mac os version are you using during install?

I just uploaded 0.4.0a1 to pypi, it might be worth trying that.

Edit: Now 0.4.0rc2; I have been able to install both bqskit==1.0.4, bqskitrs==0.4.0rc2, and bqskitrs==0.3.0 successfully on a mac m1. Are you installing the [ext] packages? There have been reported issues between those packages.

**Comment by natestemen** [comment]
Sorry for the late reply! The failure is happening on GitHub actions, so the masOS version is 12.6.4 [[build link](https://github.com/unitaryfund/mitiq/actions/runs/4671983753/jobs/8273645986)]. The download works fine for linux and windows with python 3.8, just not mac. When loosening the bqskit version requirement to `bqskit>=1.0.0` pip will install `bqskitrs==0.2.3` as seen [here](https://github.com/unitaryfund/mitiq/actions/runs/4671983753/jobs/8273645986).

> Are you installing the [ext] packages?

No, we actually [removed](https://github.com/unitaryfund/mitiq/pull/1663/files#diff-cdde4d4751f711bb59b74a062edfaa0d244ae969f7a0fbea7db0951f4c1f501fL29-R29) the requirement to install the extra packages since we only needed cirq, and you need cirq installed to use mitiq.

Anyway, it's not super urgent, and I'm fine loosening the dependency requirement, but just wanted to provide some more information in case you wanted to dig further into this.

**Comment by edyounis** [comment]
Not hearing that this issue is ongoing, I am going to close the issue. Feel free to re-open at any time. Hoping that with the upcoming 1.1 release we bury all the installation issues for good.
