### ISSUE TITLE
Potential `matrix_residuals` bug?

### ISSUE THREAD

**Issue by mtweiden** [BQSKit/bqskitrs#12]
@WolfLink and I were looking through the `matrix_residuals` function code and there might be a bug with regards to residual values not being resilient to global phase.

As written right now, the function just finds $Re(B A^\dagger) - I$. The reason this does not alway work is because if $A = e^{i \theta} U$ and $B = U$, then $B A^\dagger = e^{-i\theta} UU^\dagger = e^{-i\theta} I $. So taking the real part will generally not be the identity. 

Maybe there's a stage of preprocessing that happens beforehand that we missed?

**Comment by edyounis** [comment]
During the early days of unitary synthesis, we (really Ethan) found that doing it this way yielded better results. It may be worth a revisit, as a lot has changed since then. Do you have any thoughts on how to make the residual function global phase agnostic?

**Comment by WolfLink** [comment]
I couldn’t come up with a good way to make it phase agnostic, and experimentally found that it generally didn’t matter (presumably because we were using ansatz circuits that had extra parameters in them, and that’s enough to capture the global phase).

**Comment by WolfLink** [comment]
The problem of making those matrix residuals phase agnostic is equivalent to the problem of finding a unique representation for a unitary-up-to-a-phase, which iirc is an unsolved problem, but one that Ed was working on at some point.


It also might be possible to find an approach based on the Hilbert Schmidt norm that results in a smaller number of residuals but is phase agnostic.

**Comment by mtweiden** [comment]
I'll add a python implementation of finding canonical representations of unitaries later this weekend and ping this thread when it's done.

**Comment by edyounis** [comment]
I agree with Marc. When [Bqskit Issue 117](https://github.com/BQSKit/bqskit/issues/117) gets resolved, this won't matter at all since we can always replace the lost global phase. I am going to close this for now, but Mathias please make a PR for that canonical representation of unitaries in BQSKit. It will be greatly appreciated.
